### ISSUE TITLE
Le bouton suivant n'est pas clicable instantannément

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/ecolab-climat#102]
Avant de rentrer dans l'issue en elle-même, je me permets un retour général concernant l'outil : 
whoaaaa ! Mais on en parle de comment ce que vous avez fait, c'est ULTRA-stylé ! :heart_eyes: 
Merci beaucoup beaucoup !

Je vais faire plusieurs issues

---

J'étais sur mobile et pleins de fois, je répondais à une question, mais le bouton suivant n'était pas cliquable. Il le devenait au bout d'un moment, mais je n'ai pas compris l'intérêt ou le sens de ce délai

**Comment by laem** [comment]
C'est un délai volontaire pour éviter de faire trop de calculs. A voir avec #6 qui a récemment changé les boutons du formulaire :)

**Comment by mquandalle** [comment]
Normalement c'est corrigé via #135

**Comment by laem** [comment]
Je ferme en attendant des retours :)
