### ISSUE TITLE
Chrome et retour arrière

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-climat#104]
ne fonctionne pas sur chrome (mac) dernière version
et je ne peux pas revenir en arrière pour changer une donnée…

**Comment by martinregner** [comment]
Deux autres retours utilisateurs :
 
1. Sur Firefox :
> après avoir fait le test, j’aurais souhaité savoir comment remettre à zéro, revenir aux étapes précédentes. Si je clique sur « revenir à ma simulation », cela revient sur la même page (de résultat). 

✔️ Contourné en supprimant l'historique (cookie et cache) : cela refonctionne


2. Navigateur non précisé :
> je n’arrive pas à le remettre à «zéro » : la page me donne les résultats du test effectué la semaine dernière. Jje ne peux pas faire une nouvelle simulation

**Comment by laem** [comment]
Pour le retour en arrière, voir #27 
Pour effacer ses données, il nous faudra des retours plus précis pour corriger l'éventuel problème : bouton pas vu ? bouton qui ne marche pas ?

**Comment by laem** [comment]
> ne fonctionne pas sur chrome (mac) dernière version

je viens de tester, sur chrome + mac dernières versions, tout fonctionne. Je ferme en attente de plus d'informations pour corriger le problème.

**Comment by martinregner** [comment]
> Pour effacer ses données, il nous faudra des retours plus précis pour corriger l'éventuel problème : bouton pas vu ? bouton qui ne marche pas ?

Le bouton est vu : au clic c'est la dernière page (résultat) qui est chargée à nouveau ; pas possible de revenir en arrière.
