### ISSUE TITLE
Ne se lance pas sur Edge

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-climat#105]
![image](https://user-images.githubusercontent.com/46482115/94151829-24335d80-fe7b-11ea-9ef2-e0b3ecdc15a4.png)

**Comment by laem** [comment]
Le vieux Edge va être mis en fin de vie très bientôt, officiellement abandonné par Microsoft en mars 2021. [Source](https://9to5google.com/2020/08/18/microsoft-edge-legacy-replaced-chromium/)

En conséquence, et vu nos importantes contraintes budgétaires, je suis dans le regret de devoir ignorer cette issue : nous pouvons simplement conseiller aux utilisateurs d'utiliser Firefox ou le nouveau Edge.
