### ISSUE TITLE
Bouton pour refaire le quizz

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-climat#110]
Serait il possi de faire un bouton "Refaire le quizz" ?
Ce serait intéressant de voir comment en changeant juste un paramètre, on pourrait avoir un impact plus bénéfique pour la planète :) (par exemple, en ne prenant plus l'avion etc...)

Bonne journée !

**Comment by laem** [comment]
Ce bouton est disponible, c'est "Revenir à ma simulation" puis "Modifier mes réponses". 
En l'absence d'informations en plus (un bug qui ne ferait pas apparaître ces boutons), je ferme. 

Peut-être #106 ?
