### ISSUE TITLE
Lister les fiches élaborées 

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-climat#131]
Elles sont sur cette branche https://github.com/betagouv/ecolab-data/tree/fiches-elaborees

Peut-être aussi faire une page qui donne accès à toutes ces fiches, genre /fiches-plus ?

**Comment by martinregner** [comment]
> Peut-être aussi faire une page qui donne accès à toutes ces fiches, genre /fiches-plus ?

@laem, en vue de la sortie, oui plutôt **commencer par cette page d'accès à tout** pour faciliter l'intégration des fiches élaborées.
ℹ️ Surtout que certaines fiches élaborées ne seront pas encore rattachées à des fiches simplifiées au début.

Un bouton tout en bas de la liste de fiches simplifiées ? "ℹ️ En savoir plus sur les actions possibles" ?
![image](https://user-images.githubusercontent.com/46482115/100618438-2521b900-331c-11eb-9b8b-7b3b81e24728.png)

**Comment by laem** [comment]
J'ai mis en ligne les fiches élaborées. Il suffit maintenant d'en ajouter dans data/actions/plus avec comme nom de fichier le chemin exact des variables d'actions à rattacher.

Benjamin-Boisserie-ABC

https://github.com/betagouv/ecolab-data/tree/master/data/actions/plus
