### ISSUE TITLE
Proposition mise à jour À propos

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-climat#136]
> **Qu'est-ce que c'est ?**
> Ce simulateur vous permet d'évaluer votre empreinte carbone individuelle, puis de la situer par rapport aux objectifs climatiques.
> Il est basé sur le modèle MicMac des associations Avenir Climatique et TaCa.

_Proposition :_
_Ce simulateur vous permet d'évaluer votre empreinte carbone individuelle annuelle totale et par grandes catégories (alimentation, transport, logement, divers, services publics, numérique), de la situer par rapport aux objectifs climatiques et surtout de passer à l’action à votre niveau avec des gestes personnalisés en fonction de vos réponses._

> **Qui le développe ?**
> Il est principalement développé par l'équipe Ecolab de l'ADEME et l'association ABC, et porté par l'incubateur de la direction du numérique beta.gouv.fr.

_Proposition :_
_Il est principalement développé par l’[Association Bilan Carbone](https://www.associationbilancarbone.fr/) et l’[ADEME](https://www.ademe.fr/), avec l’appui technique et méthodologique de l'incubateur de la direction du numérique [beta.gouv.fr](https://beta.gouv.fr/) visant à concevoir des services numériques simples et faciles à utiliser._

> Le code de ce site est libre.

Changer le lien pour : https://github.com/betagouv/ecolab-data/blob/master/CONTRIBUTING.md 
(plutôt que futureco 😉 )

**Comment by laem** [comment]
Merci pour la coquille futureco ! Les dangers du fork 😰
