### ISSUE TITLE
Ok sur Firefox, petit bug sur Brave

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-climat#172]
Bonsoir, 
Merci à l'équipe pour ce joli travail avant toute chose.
Pour info, sur la navigateur brave 1.10.97, qui a tendance à bloquer certaines fonctionnalités pour réduire l'empreinte de la navigation, la fonction de total ne fonctionne pas. 
Rien d'alarmant, sur Firefox ça fonctionne impeccablement bien :-)

**Comment by laem** [comment]
Salut ! Merci pour le retour. Je me demande bien ce qui plantait :thinking: 
En tout cas, sur la 1.19 sur ubuntu, ça fonctionne aujourd'hui.

Si tu as de nouveau un bug n'hésite pas, je tâcherai d'être plus rapide sur la réponse :sweat_smile: 

![Capture d’écran du 2021-02-01 10-07-18](https://user-images.githubusercontent.com/1177762/106437231-5a11cf80-6475-11eb-83dc-d5a67aed457a.png)
