### ISSUE TITLE
Faites une présentation avec le detail des sous-rubriques en camenbert

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-climat#187]
Bonjour, 
j'ai fais le test mais la presentation de mes chiffres ne permet pas de savoir quelle est la fraction d'émission due )à la voiture et due à l'avion. Je ne sais pas conclure quelle est le levier le plus interessant.  Est ce diminuer mes km en voiture ou diminuer mes km en avion ... ? Ce serait bien de faire pour chaque rubrique (transport, logement, alimentation, ...), une presentation graphique qui détaille la proportion de chaque sous-rubrique (auto, avion, bus, ...). 
Je vous suggère de favoriser davantage les presentations graphiques (camenbert) aux présentations de "bêtes" chiffres isolés.

**Comment by laem** [comment]
J'exclut le camembert qui est une représentation graphique très critiquée mais ce format là me semble répondre au besoin : 

![image](https://user-images.githubusercontent.com/1177762/107387607-4ad5f600-6af5-11eb-8196-97cd3a989a3a.png)
