### ISSUE TITLE
Rubrique : "Modifier mes réponses"

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [betagouv/ecolab-climat#21]
Quand on click sur "Modifier mes réponses" il est difficile de savoir quelles variables correspondent à quelles questions.

Ex : il y a deux fois "heures par semaine"

Envisager d'expliciter un peu plus les variables 
"km" --> "km parcourus en voiture"
"Age" --> "age du véhicule"
"heures par semaine" --> "heures passées en tram/métro par semaine"
"heures par semaine" --> "heures passées en bus par semaine"
Etc.

**Comment by laem** [comment]
Bien vu, c'est lié à ecolab-data/issues/19

**Comment by laem** [comment]
Fixed by  #49
