### ISSUE TITLE
Message d'accueil : carbone ou climat ?

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [betagouv/ecolab-climat#22]
Je remplacerai "empreinte climat personnel" par "empreinte carbone individuelle" étant donné que la question en haut pose déjà la question "Connais-tu ton empreinte sur le climat ?"

A discuter !

**Comment by laem** [comment]
Oui c'est une question qui revient souvent. Personnellement j'évite de parler d'empreinte carbone, sauf quand il s'agit uniquement du CO2 (par exemple les budgets du GIEC), pour 2 raisons : 
- le terme carbone est vieux à ma connaissance, datant du moment où l'on parlait de kg de C, avec un facteur de conversion vers le CO2
- parler d'empreinte climat permet de ne pas restreindre au seul CO2, et donc ouvrir au méthane, protoxyde d'azote, à la vapeur d'eau, sans faire peur avec des symboles chimiques

**Comment by laem** [comment]
Cela dit, rien que pour le SEO, c'est bien d'avoir le terme "carbone" car il reste largement utilisé :) 
Je fais le changement vers ta proposition, mais on peut continuer à en discuter ici.

**Comment by fjg** [comment]
Pourrait-on concerver MicMac "Mon Impact Carbone, Mes Actions Concrètes" qui a le mérite de :

* faire lien avec l'historique et reconnaitre le travail accompli jusque là (bcp d'asso ont ce nom en tête, le connaisse...)
* permettre à AC d'intégrer le nouveau MicMac aussi sur leur site et d'autres pourraient le faire. On centraliserait le suivi des stats (affichage, complétude de simulation, temps de simulation beaucoup plus largement du coup...)
* pour traiter le sujet carbone vs autre GES, on pourrait y mettre une phrase qui explique MicMac et dire qu'on tient compte de tous les GES (carbone, méthane, ...) avec un affichage en équivalent CO2
* niveau SEO, pareil on capitalise sur le nom et les mots clés qui font sens (carbone)

Reste à valider avec AC s'ils sont ok. Côté ABC, @Benjamin-Boisserie-ABC vous en dites quoi ?
