### ISSUE TITLE
Intégrer le paquet NPM publicodes

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-climat#6]
L'intégration ne sera pas une mince affaire, mais ça simplifiera énormément ce code et l'arrivée de nouveaux développeurs.

https://www.npmjs.com/package/publicodes

**Comment by laem** [comment]
Voir si la mise à jour résout ce problème de précision des calculs 

![image](https://user-images.githubusercontent.com/1177762/86607567-b4af7f80-bfa9-11ea-9307-31a9d4e0db4f.png)

**Comment by tvisentin** [comment]
Est-ce qu’un enrichissement du paquet publicodes avec vos nouvelles mécaniques est prévu ?

**Comment by laem** [comment]
Actuellement, il n'y a pas beaucoup d'améliorations de publicodes intégrées. De mémoire, il y a un mécanisme en plus (correspondance). Mais oui clairement l'objectif est qu'Ecolab contribue à publicodes (actuellement développpé sur github.com/mon-entreprise, mais ça peut évoluer :) )

**Comment by laem** [comment]
Lire https://github.com/betagouv/mon-entreprise/issues/1126
