### ISSUE TITLE
[UX] afficher/revenir aux valeurs par défaut

### ISSUE THREAD

**Issue by sdenier** [betagouv/ecolab-climat#61]
Quand on entre une donnée dans un champ, cela modifie immédiatement le calcul (en + ou en -) et donc l'affichage dans le graphique. C'est (un peu) surprenant car on ne sait/voit pas de quelle valeur on est parti.

Si on supprime la donnée dans le champ, on ne revient pas à cette valeur par défaut - le simulateur prend la valeur 0.

L'affichage de cette valeur par défaut (=valeur moyenne je suppose) permettrait de se comparer à cette base et/ou de faciliter des simulations.

**Comment by laem** [comment]
Bonne remarque. 

Je lie ça à #6 , car la fonctionnalité a été ajoutée à betagouv/mon-entreprise, donc il s'agira de mettre à jour les composants de /conversation pour l'intégrer.

Mais c'est un travail assez lourd techniquement de faire cette migration.

**Comment by laem** [comment]
#6 est terminé, et c'est le nouveau comportement. Si on supprime la donnée, la valeur par défaut est utilisée.
