### ISSUE TITLE
Pouvoir ajuster une réponse après avoir affiché les résultats

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-climat#73]
En voyant les résultats du calculateur, je me rends compte que j'ai mal répondu à une question. J'aimerais modifier ma réponse pour affiner les résultats. Je ne trouve pas comment faire.

**Comment by laem** [comment]
Il est possible de modifier ses résultats en cliquant sur "Mes réponses". Je garde cette issue le temps de voir si c'est un problème isolé ou non. 
A noter : on a prévu de faire en sorte qu'un clic sur le bouton ◀ du navigateur fasse revenir à la question précédente. Peut-être que c'est ce que cet utilisateur attendait.

**Comment by laem** [comment]
Autres retour proche : 

> laisser la possibilité de retour arrière lors du changement de thème
