### ISSUE TITLE
Mettre une couleur différente pour les étiquettes finance/logement/conso, etc

### ISSUE THREAD

**Issue by capudav** [betagouv/ecolab-climat#8]

**Comment by laem** [comment]
@capudav je crois que c'est ce que j'ai fait dans #7 

C'est bien ça ? 

![image](https://user-images.githubusercontent.com/1177762/83501878-153a3100-a4c1-11ea-86a8-6f2bb9b6da6d.png)

![image](https://user-images.githubusercontent.com/1177762/83501912-1ff4c600-a4c1-11ea-86a9-364dde059b8d.png)
