### ISSUE TITLE
A propos des suggestions de réponse

### ISSUE THREAD

**Issue by QuentinBrch** [betagouv/ecolab-climat#84]
On pourrait préciser que les suggestions de réponses dans le calculateur sont justement des suggestions et non pas les seules réponses possibles. Il faudrait montrer qu'il est possible de personnaliser sa réponse, car j'ai trouvé que ce n'était pas forcément intuitif de remplir la case manuellement, au moins au début du quiz.

**Comment by laem** [comment]
Je ne suis pas sur qu'en précisant "suggestions", l'utilisateur qui n'a pas vu le champs de saisie, le voie davantage. 
Voir #6 . Dans la dernière version de la bibliothèque, que je mettrai à jour au plus vite, le champs est largement mis en avant par rapport aux suggestions. 

![image](https://user-images.githubusercontent.com/1177762/91883290-85a14b80-ec84-11ea-99ad-cf7b4b7f4ab9.png)


Penses-tu que ça peut résoudre le problème ?

**Comment by laem** [comment]
Je ferme, faute d'informations supplémentaires.
