### ISSUE TITLE
Création d'un paquet NPM

### ISSUE THREAD

**Issue by tvisentin** [betagouv/ecolab-climat#90]
Le but est de pouvoir facilement intégrer le calculateur et pouvoir ajouter notre design des questions / catégories / ordre des questions etc.
Avec ce paquet nous pourrons aussi avoir accès plus facilement au retour du calculateur pour pouvoir l’enregistrer chez nous, pouvoir refaire que le calcul sur les transports ou sur l’alimentation, ajouter nos calculs (en yaml) par exemple.

**Comment by laem** [comment]
@tvisentin depuis hier, nous sommes passés à une dépendance NPM au paquet publi.codes
ça permet simplement de charger cette dépendance, d'y injecter les règles YAML compilées dans betagouv/ecolab-data, et hop on peut faire des calculs. 
ça ne donne pas accès à l'interface de simulation, mais ça me semble compliqué à ce stade de proposer en paquet NPM notre interface. 
Qu'en penses-tu ? ça répond à ton besoin ?

**Comment by tvisentin** [comment]
Bonjour, merci beaucoup pour cette maj, je vais transmettre à l'équipe ! Pour le moment, nous sommes partis sur de l'iframe avec la solution et on laisse l'utilisateur reporté les résultats une fois le questionnaire fini.
Je close l'issue car on ne va pas tout de suite intégrer le paquet mais je pense que ou ça répond à notre besoin ;)

**Comment by laem** [comment]
> on laisse l'utilisateur reporté les résultats une fois le questionnaire fini.

Si on permettait à l'utilisateur d'exporter ses résultats d'une façon ou d'une autre, par exemple via une URL en GET qui contiendrait les paramètres de simulation, ou en JSON, ça vous intéresse du coup ?
