### ISSUE TITLE
Le lien dans la description du dépôt GitHub est mort

### ISSUE THREAD

**Issue by austil** [betagouv/ecolab-climat#93]
Bonjour, petite broutille (qui m'a quand même agacé 30sec) :
le lien dans la description du dépôt GitHub https://ecolab.ademe.fr/apps/micmac/simulateur/climat mène vers une page non trouvée (404). Il devrait pointer vers https://ecolab.ademe.fr/apps/climat

Beau travail sur ce simulateur !
En vous souhaitant une bonne journée.

**Comment by laem** [comment]
Salut ! Merci pour le retour, j'avais pas vu ton message :sweat: 
C'est corrigé, vers le nouveau site dédié :)
